# Generated by Django 3.0.5 on 2020-04-30 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metahumans', '0003_metahuman'),
    ]

    operations = [
        migrations.AddField(
            model_name='metahuman',
            name='ally',
            field=models.BooleanField(default=True),
        ),
    ]
